spring:
  kafka:
    consumer:
      group-id: market-data-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 5
    listener:
      ack-mode: manual
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
# Market Data Configuration
market:
  data:
    symbols: BTC-USD,ETH-USD,ADA-USD,SOL-USD

