spring:
  application:
    name: executor-service
  config:
    import: "zookeeper:"
  data:
    rest:
      base-path: /

# Server Configuration
server:
  port: 8080

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always