spring:
  application:
    name: analysis-service
  config:
    import: "zookeeper:"
  data:
    rest:
      base-path: /
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      group-id: analysis-service-group
      auto-offset-reset: earliest
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://timescaledb:5432/centinel_test}
    username: ${SPRING_DATASOURCE_USERNAME:centinel_test}
    password: ${SPRING_DATASOURCE_PASSWORD:postpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Enable TimescaleDB extension
        jdbc:
          time_zone: UTC
    show-sql: false
# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
# Server Configuration
server:
  port: 8080
signal:
  config:
    rsiPeriod: 14
    emaShort: 12
    emaLong: 26
    macdSignal: 9
    arbitrageThreshold: 0.0025
# Multi-timeframe Analysis Configuration
analysis:
  multi-timeframe:
    enabled: true
    short-term-interval: 30000  # 30 seconds
    long-term-interval: 300000  # 5 minutes
    status-log-interval: 60000  # 1 minute
    min-signal-strength: 0.3
    timeframes:
      - M1
      - M5
      - M15
      - H1
      - H4
      - D1

# Logging Configuration
logging:
  level:
    com.fedelis.centinel.analysis: INFO
    org.springframework.kafka: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
